{"uuid": "4e5cc4d2-259e-4fbd-840e-078b44828af5", "children": ["9a94b0d9-2d33-4828-9fae-4f8746af2763", "12b326ec-ffcf-4480-9289-493fc276ac7c", "5571074b-815f-42a7-ad59-d93294914f28", "9c7b8d1d-c778-426b-8ccd-b8c762074093", "516c0440-a9b8-4b73-be8c-7333caa92f86", "07e1a280-0d2f-4d17-8184-e792b7068872", "99b3216f-490e-42f7-bc48-e63e9a53a690", "a7dba4c6-1c85-4cb1-966a-0844140ca7b3", "dc5fb544-14c0-424f-bf84-24f5d53c59ba", "24cb7d1b-2b46-44a9-a54b-0686bd5de89f", "c77033f4-1896-4c4c-847c-ddf299bbb4ff", "09ff0f0b-e94e-413e-a033-bc0c5341d6bf", "19bc3e69-b043-418a-b484-4527e867dcc3", "dcc728ba-1687-4118-b133-8ebb7bb7e460", "bd6e9fc6-ca84-4a8c-9e7a-1d46390a934c", "0af80273-5b2c-43bd-938b-f3b4f816aae4", "542fee22-8af5-45b0-b5bf-f40842ee2b6a", "2d6a1a66-9477-4d93-ad88-895f544b0273", "92cd333c-7753-4da0-80d6-faf1dd6394fe"], "befores": [{"name": "system_login", "status": "failed", "statusDetails": {"message": "Failed: 接口请求异常，可能是request的连接数过多或请求速度过快导致程序报错！\n", "trace": "  File \"D:\\pythonProject\\lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n  File \"D:\\pythonProject\\lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"D:\\pythonProject\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"D:\\pythonProject\\lib\\site-packages\\pluggy\\_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\pythonProject\\lib\\site-packages\\_pytest\\fixtures.py\", line 1195, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\pythonProject\\lib\\site-packages\\_pytest\\fixtures.py\", line 929, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"D:\\wjl_pyt\\pythonproject\\testcase\\conftest.py\", line 30, in system_login\n    RequestBase().specification_yaml(api_info[0][0], api_info[0][1])\n  File \"D:\\wjl_pyt\\pythonproject\\base\\apiutil.py\", line 98, in specification_yaml\n    res = self.run.run_main(name=api_name, url=url, case_name=case_name, header=header, method=method,\n  File \"D:\\wjl_pyt\\pythonproject\\common\\sendrequest.py\", line 155, in run_main\n    response = self.send_request(method=method,\n  File \"D:\\wjl_pyt\\pythonproject\\common\\sendrequest.py\", line 111, in send_request\n    pytest.fail(\"接口请求异常，可能是request的连接数过多或请求速度过快导致程序报错！\")\n  File \"D:\\pythonProject\\lib\\site-packages\\_pytest\\outcomes.py\", line 177, in fail\n    raise Failed(msg=reason, pytrace=pytrace)\n"}, "attachments": [{"name": "接口名称：用户登录", "source": "f26734db-0d27-487d-96f4-06d63b2d3788-attachment.txt", "type": "text/plain"}, {"name": "接口地址：http://127.0.0.1:8787/dar/user/login", "source": "0928ef31-9edd-47e9-b0db-c976323dc307-attachment.txt", "type": "text/plain"}, {"name": "请求方法：post", "source": "43cfc721-fb07-4fe2-a41c-b4bc52ac95ca-attachment.txt", "type": "text/plain"}, {"name": "请求头：{'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8'}", "source": "65d04e8d-677b-4586-9cf2-0548cc59d0e7-attachment.txt", "type": "text/plain"}, {"name": "测试用例名称：用户名和密码正确登录验证", "source": "342ae66d-3a04-4e56-8225-2992aca2adec-attachment.txt", "type": "text/plain"}, {"name": "请求参数", "source": "1b28b573-c36b-4c42-a627-d930f9d04e64-attachment.txt", "type": "text/plain"}], "start": 1753540658369, "stop": 1753540660444}], "start": 1753540658369, "stop": 1753540665542}